name: ouija_quiz_game
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.0
  built_value: any
  built_collection: any
  flare_flutter: ^1.2.2
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  built_value_generator: any


flutter:

  uses-material-design: true

  assets:
    - assets/OuijaOpenPage.flr
    - assets/OuijaLoadingPage.flr
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf